anything-market/don-t-buy-macat

src/components/error/error.style.jsx
src/styles/theme.jsx

- 404Page UI 구현했습니다. 
- 홈으로 이동 버튼을 누르면 홈으로 이동합니다.
close: #4 
스타일 컴포넌트가 제대로 작성되었는지 확인부탁드립니다.

404Page UI 구현

---

src/components/header/BasicHeader/BasicHeader.jsx
src/components/header/BasicHeader/basicHeader.style.jsx
src/components/header/ChatHeader/ChatHeader.jsx
src/components/header/ChatHeader/chatHeader.style.jsx
src/components/header/MainHeader/MainHeader.jsx
src/components/header/MainHeader/mainHeader.style.jsx
src/components/header/SearchHeader/SearchHeader.jsx
src/components/header/SearchHeader/searchHeader.style.jsx
src/components/header/UploadHeader/UploadHeader.jsx
src/components/header/UploadHeader/uploadHeader.style.jsx

- 페이지별 헤더 컴포넌트의 UI를 구현했습니다
- 검색버튼을 누르면 user/search페이지로 이동하여 서치 헤더가 보이도록 구현했습니다
- 메인 헤더 컴포넌트를 중심으로 코드를 봐주시면 감사하겠습니다
- 스타일 컴포넌트의 사용에 있어서 더 발전시킬 부분은 없을지 봐주시면 감사하겠습니다

feat: 헤더 컴포넌트 UI 구현

---

src/assets/img-button.svg
src/components/sign-in/SetProfile.jsx
src/components/sign-in/SignIn.jsx
src/components/sign-in/setProfile.style.jsx
src/components/sign-in/signin.style.jsx
src/pages/Pages.jsx

- 라우터 페이지에 컴포넌트를 추가했습니다.
- 풀 받으신 후 각자 필요한 라우터페이지 생성해서 푸시하면 되겠습니다!
close: #

chore: Pages에 SignIn, setProfile 페이지 라우터 추가

---

src/components/postUpload/PostUpload.jsx
src/components/postUpload/postUpload.style.jsx

- 헤더 컴포넌트 추가
- 게시물 작성 페이지 UI 구현 
- 게시글을 작성할 수 있습니다
- 하단 이미지 업로드 아이콘을 누르면 로컬파일 저장소가 열립니다. (업로드 기능은 추후에 추가 할 예정입니다)
-사진공간에 엑박이 뜨고 있습니다. 업로드 기능은 추가를 하지 못한 상태라 사진이 들어갈 공간 UI만 만들어 놓은 상태입니다.
close: #28 
불필요한 코드가 없는지 확인해주시면 감사하겠습니다.

feat: 게시물 작성 페이지 UI구현

---

src/components/sign-in/SetProfile.jsx
src/components/sign-in/SignIn.jsx
src/components/sign-in/signin.style.jsx
src/pages/Pages.jsx

- 회원가입을 위한 기능구현
- useEffect사용하여 email, password 인풋값이 바뀔때마다 유효성검사 진행
- 유효성검사 통과하지 못할 시 메세지 출력
- email, password 둘 다 true일 때 다음버튼 활성화
- 다음버튼 누를 시 서버에 post요청
- response결과값에 따라 회원가입 진행 혹은 메세지 출력
- 유효성검사 진행하여 메세지 출력 및 버튼 비활성화
- 유효성검사 진행시 메세지 숨김 및 버튼 활성화
- 버튼 활성화시 primary색으로 변경기능 추가 예정
close: #30 #38 
- 유효성검사 예외처리가 잘 된건지 중심으로 봐주시면 감사하겠습니다!

feat: 회원가입 이메일/비밀번호 유효성검사 기능구현

---

src/components/adoptPost/AdoptPost.jsx
src/components/adoptPost/adoptPost.style.jsx
src/components/header/BasicHeader/BasicHeader.jsx
src/components/header/BasicHeader/basicHeader.style.jsx
src/components/header/ChatHeader/ChatHeader.jsx
src/components/header/ChatHeader/chatHeader.style.jsx
src/components/header/MainHeader/MainHeader.jsx
src/components/header/MainHeader/mainHeader.style.jsx
src/components/header/SearchHeader/SearchHeader.jsx
src/components/header/SearchHeader/searchHeader.style.jsx
src/components/header/UploadHeader/UploadHeader.jsx
src/components/header/UploadHeader/uploadHeader.style.jsx
src/components/header/commonHeader.style.jsx

- 헤더 position 변경 : 마크업 순서에 상관없이 상단에 고정되도록 fixed로 수정하였습니다
- 입양 등록 페이지 UI만 구현하였습니다
- 특이 사항
close: #23 
- 추후 헤더 컴포넌트는 하나도 통합하는 게 좋을 것 같은데, 우선 베이직 헤더 레이아웃 스타일만 겹쳐서 해당 스타일만 하나의 파일로 묶어주었습니다. 
- 입양 등록 페이지는 기능을 만들기 위해 우선 UI 부터 빠르게 구현해보았습니다. 
- 입양 등록 페이지 UI에 혹시 놓친 부분이 없는지 확인해주시면 감사하겠습니다!

Feature/adoption post page UI

---

src/components/login/Login.jsx
src/components/sign-in/SignIn.jsx

- 이메일 인풋값이 비어있을 때에도 경고메세지 출력되는 현상 제거
- 이메일 인풋값이 비어있을 때 setEmailMessage 빈 값으로 세팅
- 경고창 출력 후 다시 인풋값을 비워줬을 때 경고창 사라짐
close: #1

feat: 로그인 기능 구현

---

src/components/login/Login.jsx
src/components/sign-in/SetProfile.jsx
src/components/sign-in/SignIn.jsx
src/components/sign-in/setProfile.style.jsx

- 회원가입을 위한 기능 구현
- 로그인 화면의 '이메일로 회원가입' 클릭시 회원가입 페이지로 링크
- 이메일/비밀번호 입력시 유효성검사 진행 -> 검사 통과시 버튼 활성화
- 버튼 클릭시 서버에 데이터 전송 / 사용가능한 이메일 or 이미가입된 이메일 응답
- 프로필 설정페이지에서 FileReader통한 미리보기 구현
- 미리보기 사진 업로드시 서버에 데이터 전송 -> filename획득
- 폼 유효성검사 진행 -> 검사 통과시 버튼 활성화
- 버튼 클릭시 서버에 formData형태로 data 전달
- 계정 유효성검사 진행
- 통과시 회원가입 성공 / home화면으로 이동
- 이메일 형식, 비밀번호 6자 이상 유효성검사 진행
- 이미 가입된 이메일주소 검사
- 다음버튼 누를시 프로필 설정페이지로 이동
- 이미지 프리뷰 및 폼작성 후 회원가입 (유저아이디, 닉네임 필수)
- 성공적으로 회원가입시 홈화면으로 이동
close: #38 #15 #13 
- 프로필 설정시 이미지를 선택했을때 실행되는 함수가 두가지 기능을 갖습니다. (이미지 src에 쓸 base64형태로 인코딩 / 서버에 전송하여 filename획득) 이 기능을 어떻게 분리하면 좋을지 감이 안오네요

feat: 회원가입 기능 구현

---

src/components/adoptSection/AdoptSection.jsx
src/components/adoptSection/adoptSection.style.jsx
src/components/modal/modalContent/PostModalContent/PostModalContent.jsx
src/components/modal/modalContent/ProductModalContent/ProductModalContent.jsx

- productModal의 컴포넌트 명이 postModalComponent로 되어있어서 올바르게 수정하였습니다
- 추가적으로 웹사이트에서 보기라는 목록이 추가된 모달이 필요하여 ProductModal 파일을 추가하였습니다
- 입양을 기다려요 section UI를 구현하였습니다. 
- 데이터를 받아와 이미지와, 이름, 가격을 보여주고 없을시 null을 반환합니다
- 요소를 클릭하면 모달이 열립니다 (아직 UI만 구현되었기 때문에 실제 삭제와 수정작업은 불가능합니다)
- 추후 기능을 개발할 예정입니다. 
- 특이 사항
close: #60 
- 스타일 컴포넌트를 효율적으로 썼는지에 집중해서 봐주시면 좋을 것 같습니다.
- 컴포넌트에 기능이 너무 많은데 이 함수들을 어떻게 분리해줄지 고민입니다. ㅠㅠ

feat: 입양을 기다려요 section UI 구현

---

src/components/comment/CommentCard.jsx
src/components/comment/CommentReply/CommentReply.jsx
src/components/post/PostCard/PostCard.jsx
src/pages/Pages.jsx
src/pages/home/Home.jsx
src/pages/post/Post.jsx

- 피드화면에서 게시글을 클릭하면 게시글 상세페이지가 뜹니다
- 헤더컴포넌트 + 피드컴포넌트 + 댓글컴포넌트 합치는 작업을 했습니다
- 피드컴포넌트 추후에 합칠 예정이라서 가운데 부분이 비어있습니다
- 댓글 리스트 모달 컴포넌트도 추후에 합치겠습니다
close: #69 
수정할 곳이 없는지 확인해주시면 감사하겠습니다

[feat] 게시글 상세페이지 화면 구현

---

src/components/postUpload/PostUpload.jsx

- base64로 인코딩한 문자열을 배열에 담아 서버에 post요청을 보내어 filename를 받습니다
- filename을 다른 정보와 함께 서버에 post요청을 보냈습니다
- 파일 업로드가 완료되면 home으로 이동합니다
사진을 선택하고 저장버튼을 누르면 서버로 전송이 됩니다.
전송이 완료되면 홈으로 이동합니다.
close: #57 
리팩토링할 때 어느 부분을 더 보완해야 될까요?

[feat] 게시글 작성페이지 업로드 기능구현

---

src/components/post/PostCard/PostCard.jsx
src/components/post/PostCard/PostCard.style.jsx
src/components/post/PostContent/PostContent.jsx
src/components/post/PostContent/PostContent.style.jsx
src/pages/home/Home.jsx

- PostContent 내 하트 버튼을 HeartBtn 컴포넌트로 리팩토링
- PostAuthor 부분 UserComponent로 변경
- Home 게시글 limit변경
close: #

[refactor] 게시글 관련 컴포넌트 및 Home 컴포넌트 리팩토링

---

src/components/header/ChatHeader/ChatHeader.jsx
src/components/header/commonHeader.style.jsx
src/components/userComponent/UserComponent.jsx
src/components/userComponent/userComponent.style.jsx
src/pages/Pages.jsx
src/pages/chats/Chat/Chat.jsx
src/pages/chats/Chat/chat.style.jsx
src/pages/chats/ChatList/ChatList.jsx
src/pages/chats/ChatList/chatList.style.jsx
src/pages/chats/TestUserInfo.jsx

- UserComponent를 사용하는 팀원과 논의해 해당 컴포넌트의 상위 태그를 Link 태그가 아닌 div태그로 바꾸었습니다. 유저컴포넌트가 재활용되는 곳이 많아서 유저컴포넌트를 사용하는 상위 컴포넌트에서 url을 설정해주는 것이 효율적일 것 같습니다. 
- 헤더에 바텀 라인을 추가했습니다.
- 채팅목록은 유저컴포넌트로 구성되어있습니다.
- 테스트 유저 정보를 만들어 임의로 유저 데이터를 만들었습니다.
- 채팅목록을 누르면 채팅 상세페이지로 넘어갑니다.
- 채팅 알림 기능은 UI만 구현해둔 후 주석처리를 통해 추후 리팩토링시 기능을 구현할 예정입니다.
- 특이 사항 : rebase로 커밋들을 모두 충돌을 해결 후 push했습니다. 커밋들을 하나하나 수정해야했기 때문에 차라리 pr을 날리고 나중에 충돌을 수정하는게 현명한 것 같습니다.ㅠㅠ
close: #25 #26
- rebase를 통해 충돌을 해결한 부분이 팀원분들의 컴포넌트에 영향을 줄 수 있기 때문에 머지 되기 전, 수정사항을 반영해야하는 부분이 있다면 말씀해주시면 감사하겠습니다.

feat: 채팅, 채팅 목록 페이지 UI 구현

---

src/components/navigation-bar/NavigationBar.jsx
src/pages/chats/ChatList/ChatList.jsx

-불필요한 z-index 속성으로 모달과 겹치는 이슈
- top border가 없음
- 채팅 페이지에 nav 컴포넌트 필요
- 작업 내역 
- 채팅 페이지에도 nav 컴포넌트 보임
- nav 정상적인 스타일로 보임
- 특이 사항
close: #80

[bug] nav 스타일로 인한 오류 수정

---

src/pages/adoptPost/adoptPost.style.jsx

- 헤더와 간격이 디자인과 달라서 작업했습니다
- 작업 내역 
- 동작 
- 특이 사항
close: #

design: 입양 등록 페이지 헤더와 간격 조정

---

src/pages/chats/ChatList/chatList.style.jsx
src/pages/userProfile/UserProfile.style.jsx

- 컨텐츠 하단부 네비바에 가려지는 현상 해결
- 컨텐츠 Wrapper요소에 padding-bottom 추가
- 하단부 겹치지 않고 보여짐
- 특이 사항
close: #

fix: 컨텐츠 하단부 네비바에 가려지는 현상 해결

---

src/components/error/error.style.jsx
src/pages/Pages.jsx

- [x ] 리펙토링 : 에러페이지 라우터 추가, 색상변경
- 공통적으로 사용하는 색상이름이 변경이 안되어있어서 수정했습니다
- 라우터 페이지에 에러페이지 추가했습니다(에러가 나면 에러페이지로 이동합니다)
- 색상변경
- 라우터페이지에 추가
close: #87

[refactor] 에러페이지 라우터 추가, 색상변경

---

src/components/comment/CommentList/CommentList.jsx
src/components/comment/CommentList/commentList.style.jsx
src/components/comment/CommentReply/CommentReply.jsx
src/components/comment/CommentReply/commentReply.style.jsx
src/components/postUpload/PostUpload.jsx
src/components/postUpload/postUpload.style.jsx

- axios, props로 사용자 프로필 사진을 불러와 프로필 이미지 추가
- 프로필 이미지 스타일 컴포넌트 수정
- 댓글페이지 프로필 사진 추가
- 게시물페이지 프로필 사진 추가
close: #91

[feat] 게시물 업로드, 댓글 컴포넌트 프로필 사진 추가

---

src/components/comment/CommentList/commentList.style.jsx
src/components/postUpload/PostUpload.jsx

[refactor] 댓글작성페이지, 게시물작성 페이지 주석제거

---

src/components/comment/CommentList/CommentList.jsx
src/utils/timeForToday.js

- 실시간 시간 출력하는 함수를 추가했습니다
- utils 폴더에서 timeForToday함수를 추가했습니다
close: #95

[bug, refactor] 댓글 작성시 실시간 시간 출력

---

src/components/comment/CommentList/CommentList.jsx
src/components/comment/CommentList/commentList.style.jsx

- 댓글 리스트 토글 버튼 임시로 넣어놨던거 컴포넌트로 교체했습니다
- 작업 내역 
- 토글버튼을 클릭하면 신고하기 모달이 뜹니다
close: #97

[refactor] 댓글 리스트 토글 버튼, 모달 컴포넌트 추가

---

src/components/post/PostCard/PostCard.style.jsx
src/components/post/PostContent/PostContent.jsx
src/pages/home/Home.style.jsx

- 하드코딩되어있던 게시글 작성날짜를 formatDate함수를 거쳐서 년/월/일 형식으로 표기되도록 구현했습니다.
- 동작 
- 특이 사항
close: #

[feat] 피드 게시글 내 날짜 년/월/일 형식으로 표기

---

src/components/postUpload/PostUpload.jsx

게시물  작성 후 프로필페이지로 이동합니다
- 게시글 작성 후 홈으로 바로 이동하는게 사용자 UX에 불편함이 느껴져 수정했습니다
- 게시글 작성 후 작성자의 프로필 페이지로 이동합니다
close: #104

[refactor] 게시글 작성 후 내 프로필페이지로 이동

---

firebase.json
src/components/postUpload/PostUpload.jsx

- 에러가 나도 404 에러페이지로 연결이 안되어서 수정했습니다
- firebase config파일에 설정 추가 
- 만들어 놓은 404 에러 페이지가 잘 뜹니다
close: #106

[bug] 404 에러 페이지 연결

---

src/components/postUpload/PostUpload.jsx

게시글 작성 후 홈으로 바로 이동하는게 사용자 UX에 불편함이 느껴져
수정했습니다
- [] 신규 기능 추가 : 
- 게시글 작성 후 홈으로 바로 이동하는게 사용자 UX에 불편함이 느껴져 수정했습니다
- 게시글 작성 후 작성자의 프로필 페이지로 이동합니다 
close: #

[fix] 게시글 작성 후 내 프로필 페이지로 이동

---

src/components/login/Login.jsx
src/components/sign-in/SetProfile.jsx
src/components/sign-in/SignIn.jsx

- 회원가입 성공시 로딩중 페이지 출력
- 프로필사진 설정시 비율 깨짐
- 회원가입 성공시 로그인페이지로 이동
- 프로필사진 image 속성에 object-fit속성 추가
- 회원가입 성공시 로그인페이지로 이동
- 프로필 이미지 비율에 맞게 보여짐
- 특이 사항
close: #110 #111

bug: 회원가입 성공시 로그인페이지로 이동/프로필사진 설정시 이미지 찌그러짐 해결

---

src/components/post/PostContent/PostContent.jsx
src/components/post/PostImgContainer/PostImgContainer.jsx
src/components/post/PostImgContainer/PostImgContainer.style.jsx
src/components/profile/ProfileInfo/ProfileInfo.style.jsx
src/components/userComponent/UserComponent.jsx
src/components/userComponent/userComponent.style.jsx

- 유저컴포넌트 : 프로필 이미지가 엑박일때 디폴트로 교체, 사이즈 깨지는 현상 수정
- 사용자 프로필 페이지 프로필 이미지 사이즈 깨지는 현상 수정
- 게시글 내 이미지와 텍스트 클릭하면 게시글 상세로 이동하도록 수정

[fix] 게시글 내 이미지, 유저컴포넌트 프로필 이미지 관련 수정

---

src/components/comment/CommentReply/CommentReply.jsx
src/components/header/UploadHeader/UploadHeader.jsx
src/components/post/PostAlbumCard/PostAlbumCard.jsx
src/components/postUpload/PostUpload.jsx
src/pages/home/Home.jsx
src/pages/userProfile/UserProfile.jsx

- 이유
- 로컬스토리지에 유저데이터가 남아있으면 Home이 무한로딩되는 이슈 수정하였습니다
- 필요없는 콘솔 삭제하였습니다
- Feed empty일때 검색 헤더 추가하였습니다

[fix] Home 컴포넌트 수정 및 콘솔 삭제

---

src/components/post/PostImgContainer/PostImgContainer.jsx

[feat] 게시글 내 이미지 엑박일때 디폴트 이미지로 뜨도록 교체

---

src/pages/adoptPost/AdoptPost.jsx

-입양 등록 후 입양 공고를 확인할 수 있도록 사용자 페이지로 바로 이동할 수 있도록 수정
- 데이터 전송 후 받은 응답을 통해 사용자 id를 받아 즉시실행함수로 프로필로 이동할 수 있도록 기능 구현

fix: 입양 등록 후 사용자 페이지로 바로 이동할 수 있도록 수정

---

src/components/adoptSection/AdoptSection.jsx
src/components/modal/alert/PostDeleteAlert/PostDeleteAlert.jsx
src/components/modal/modalContent/ProductModalContent/ProductModalContent.jsx

- delete 기능 구현
- 삭제 시 페이지 리로드
- 없습니다!
close: #119 
- 불필요한 코드가 없을시 빠르게 approve해주시면 감사하겠습니다!

feat: adoptSection에서 입양 등록 게시물 삭제 기능 구현

---

src/components/login/Login.jsx

- 토큰검증기능 추가
- axios get으로 token검증기능 추가
- data가 valid상태일 때만 local storage에 유저정보 추가
- valid하지 않거나 axois실패시 콘솔에러 출력
- 토큰유효성검사 실패시 오류출력 (콘솔)
- 특이 사항
close: #125

feat: 토큰 검증기능 추가

---

src/components/profile/ProfileInfo/ProfileInfo.jsx
src/pages/Pages.jsx
src/pages/editprofile/EditUserProfile.jsx
src/pages/editprofile/EditUserProfile.style.jsx

- 기존 사용자의 프로필을 가져와 input의 value로 삽입
- id 유효성검사 추가
close: #120

[feat] 사용자 프로필 수정 기능 구현
